ssh_pwauth: no

users:
  - name: ${USERNAME}
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
    - "${SSH_KEY}"

write_files:
  - content: |
      #!/bin/bash
      set -e

      apt-get update
      apt-get install -y ca-certificates curl gnupg
      curl -fsSL https://get.docker.com | bash
      usermod -aG docker ${USERNAME}
    path: "/root/vm_prep.sh"
    permissions: "0740"

runcmd:
  - sleep 120
  - /root/vm_prep.sh